<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Clientpage_new</name>
   <tag></tag>
   <elementGuidId>2f55bde1-5040-4ea4-a05c-6cd44642bbc7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>/html/body/div[1]/main/div/div[1]/div/div[1]/ul/li/a[1]/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/div[1]/main/div/div[1]/div/div[1]/ul/li/a[1]/span</value>
   </webElementProperties>
</WebElementEntity>
