<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>newclient_branch</name>
   <tag></tag>
   <elementGuidId>c7c24322-6d87-445e-b8a3-f826dfd9a670</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;myModal&quot;]/div/div/ng-include/div[2]/form/div[4]/div/select</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;myModal&quot;]/div/div/ng-include/div[2]/form/div[4]/div/select</value>
   </webElementProperties>
</WebElementEntity>
